name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev

jobs:
  deploy_production:
    if: github.event_name == 'push' && github.ref_name == 'main'
    runs-on: ubuntu-latest
    name: Deploy Production
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy Prod
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_087943410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/AngleGameFrontend"
          api_location: ""
          output_location: "dist"
          production_branch: "main"
        env:
          VITE_API_URL: "https://angle-game-api-b9dtbce4f8g4cxhq.northcentralus-01.azurewebsites.net"

  deploy_staging:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref_name == 'dev')
    runs-on: ubuntu-latest
    name: Deploy Staging
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy Staging
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_087943410 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/AngleGameFrontend"
          api_location: ""
          output_location: "dist"
          production_branch: "main"
        env:
          VITE_API_URL: "https://angle-game-api-dev-amgsbggzdrfndma0.centralus-01.azurewebsites.net"

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_AGREEABLE_RIVER_087943410 }}
          action: "close"
