name: Inject Azure PR Permissions

on:
  push:
    branches:
      - main # Only runs when you push or merge directly into main

permissions:
  id-token: write
  contents: read

jobs:
  inject-credentials:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_CAE011B692F245AD89F8CD7180352500 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4FF360001B3B4B53A75C969D5A87D5EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E59F554249CD46D7BD7D5BC2D916943F }}

      - name: Force Add PR Federated Credential
        run: |
          az ad app federated-credential create \
            --id "cae011b6-92f2-45ad-89f8-cd7180352500" \
            --parameters '{"name":"github-pr-access","issuer":"https://token.actions.githubusercontent.com","subject":"repo:Sendecki-Krzysztof/AngleGame:pull_request","description":"Allow PR testing","audience":["api://AzureADTokenExchange"]}'
