name: Azure Function Apps CI/CD

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
      - dev
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: "AngelGameBackend"
  PYTHON_VERSION: "3.13"

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create virtual environment and install dependencies
        working-directory: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: "Deploy to Azure Functions"
        uses: Azure/functions-action@v1
        with:
          # Dynamically target the Prod App or the Dev App
          app-name: ${{ (github.event_name == 'push' && github.ref_name == 'main') && 'angle-game-api' || 'angle-game-api-dev' }}

          # Dynamically use the correct VIP pass
          publish-profile: ${{ (github.event_name == 'push' && github.ref_name == 'main') && secrets.AZURE_PUBLISH_PROFILE_PROD || secrets.AZURE_PUBLISH_PROFILE_DEV }}

          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
